CryptX added priority as optional parameter and new coin
GENERALBYTESCOM/batm_public pull request #496
Opened 2021-02-03 13:10 UTC by khidesha

2021-02-05 10:00 UTC, pvyhnal-generalbytes requested changes

2021-02-05 12:15 UTC, khidesha commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/CryptXWallet.java
> +        }
USDT (Teaser) is an erc20 token and it's on ethereum blockchain. That's why for some cases cryptX wallet API needs be called with "eth" in code.

2021-02-05 19:12 UTC, khidesha commented on server_extensions_extra/src/main/resources/batm-extensions.xml
>                  <cryptocurrency>BTC</cryptocurrency>
Sorry, I can't understand. What do you mean under the tag?

2021-02-08 09:42 UTC, pvyhnal-generalbytes commented on server_extensions_extra/src/main/resources/batm-extensions.xml
>                  <cryptocurrency>BTC</cryptocurrency>
I meant the param tag, sorry.

`<param name="priority" />`

2021-02-08 18:05 UTC, khidesha commented on server_extensions_extra/src/main/resources/batm-extensions.xml
>                  <cryptocurrency>BTC</cryptocurrency>
Ok, can you confirm that all issues are corrected on our side

2021-02-09 09:35 UTC, pvyhnal-generalbytes commented on server_extensions_extra/src/main/resources/batm-extensions.xml
>                  <cryptocurrency>BTC</cryptocurrency>
yes, just please add this tag also to the cryptxnoforward

2021-02-10 06:57 UTC, generalbytes commented
We are waiting for suggested changes to be implemented.

2021-02-10 13:25 UTC, hungry-programmer commented
All requested changes have been made. Please review again.

2021-02-10 14:04 UTC, pvyhnal-generalbytes approved these changes

2021-02-16 11:06 UTC, merged