BATM-1844 server-onfido serving customer web for identity verification
GENERALBYTESCOM/batm_public pull request #520
Opened 2021-03-22 13:42 UTC by kubacech

2021-03-22 14:44 UTC, generalbytes requested changes
Remove all mentions of Onfido. 
This website should be verification service agnostic.
how about verification_site?

2021-03-23 09:34 UTC, kubacech commented
> Remove all mentions of Onfido.
> This website should be verification service agnostic.
> how about verification_site?

module renamed to verification_site

2021-03-24 12:22 UTC, generalbytes requested changes
Add also description how to compile, configure and run verification_site in existing README.md
Thank you.

2021-03-24 12:22 UTC, generalbytes commented on verification_site/src/main/resources/static/script.js
> +                    title: 'Verify Your Identity',
Add support for czech language too.

2021-03-24 12:22 UTC, generalbytes commented on verification_site/src/main/java/com/generalbytes/verification/controller/VerificationController.java
> +    public ResponseEntity register(@RequestBody RegisterNewApplicantReq req) {
Add javadoc. Mainly who call this method and why.

2021-03-24 12:22 UTC, generalbytes commented on verification_site/src/main/java/com/generalbytes/verification/controller/VerificationController.java
> +    @GetMapping("/token/{applicant}")
Add javadoc. Mainly who call this method and why.

2021-03-24 12:22 UTC, generalbytes commented on verification_site/src/main/java/com/generalbytes/verification/controller/VerificationController.java
> +    @GetMapping("/submit/{applicant}")
Add javadoc. Mainly who call this method and why.

2021-03-24 12:22 UTC, generalbytes commented on verification_site/src/main/java/com/generalbytes/verification/service/ApplicantService.java
> +    private final ConcurrentHashMap<String, Applicant> CACHE = new ConcurrentHashMap<>();
Use CacheBuilder.

Example is here: https://github.com/GENERALBYTESCOM/batm_public/blob/8f76ef5697f1a5887d98c88e324607b4e9a1270e/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/exchanges/XChangeExchange.java#L69

2021-03-24 12:22 UTC, generalbytes commented
Add also description how to compile, configure and run verification_site in existing README.md
Thank you.

2021-03-25 11:26 UTC, kubacech commented
I updated PR with requested changes.

2021-03-29 07:09 UTC, merged