feat: added BTBS ERC20 tokens
GENERALBYTESCOM/batm_public pull request #583
Opened 2021-07-25 21:42 UTC by GuillermoBlasco

Added config for fixprice, eth extension and cryptx wallet

2021-07-30 07:51 UTC, pvyhnal-generalbytes requested changes
I added a few comments regarding two-way (buy & sell) support. 
If you only need Buy support, Infura wallet should be enough and you don't need the PaymentSupport implementation.

The logos provided do not follow the style of the other crypto currency logos on the ATM, please see template.svg

2021-07-30 07:51 UTC, pvyhnal-generalbytes commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/bitcoin/wallets/cryptx/v2/CryptXWallet.java
> +        coins.add(CryptoCurrency.BTBS.getCode());
Does CryptX support BTBS? Their documentation does not mention it: 
https://api.cryptx.com/#section/Coin-Digital-Currency-Support

2021-07-30 07:51 UTC, pvyhnal-generalbytes commented on server_extensions_extra/src/main/resources/batm-extensions.xml
> +                <cryptocurrency buyonly="true">BTBS</cryptocurrency>
Are you adding two-way (buy & sell) or just one way (buy only) support for BTBS?
Here you specify "buyonly=true" and in that case you do not need to implement the "PaymentSupport" interface.

2021-07-30 07:51 UTC, pvyhnal-generalbytes commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/ethereum/erc20/btbs/BtbsPaymentSupport.java
> +public class BtbsPaymentSupport extends QueryableWalletPaymentSupport {
QueryableWalletPaymentSupport would only work with coinbase wallet for now

2021-07-30 08:15 UTC, GuillermoBlasco commented
Thanks! We'll review it and update the PR.

2021-08-17 14:21 UTC, GuillermoBlasco commented
Logos updated, and code fixed. Still waiting for Cryptx confirmation. Thanks pvyhnal-generalbytes

2021-08-19 20:45 UTC, GuillermoBlasco commented
Hey @pvyhnal-generalbytes ! We have confirmation from Cryptx that BTBS is already supported! It is not listed in their API documentation because they support +100 ERC20 tokens, so they don't list them all. But we have confirmation.

Therefore, is it ready for review and merge? 

Thanks!

2021-08-20 09:27 UTC, merged