Simple coin
GENERALBYTESCOM/batm_public pull request #611
Opened 2021-09-02 09:10 UTC by martinkyov

2nd attempt

2021-09-06 08:42 UTC, pvyhnal-generalbytes approved these changes

2021-09-06 11:27 UTC, filipocelka requested changes

2021-09-06 11:27 UTC, filipocelka commented on server_extensions_extra/src/test/java/com/generalbytes/batm/server/extensions/extra/simplecoin/sources/SimpleCoinRateSourceTest.java
> +public class SimpleCoinRateSourceTest {
Empty class, please remove it

2021-09-06 11:27 UTC, filipocelka commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/simplecoin/sources/SimpleCoinRateSource.java
> +        log.debug("Unsupported currency");
Useless log message - what is unsupported? Add `cyptoCurrency` and `fiatCurrency` to log message or remove this line

2021-09-07 06:49 UTC, filipocelka approved these changes

2021-09-16 11:18 UTC, merged