Cf 212 improve performance find identities
GENERALBYTESCOM/batm_public pull request #647
Opened 2021-11-10 06:40 UTC by mmyslivec-GB

2021-11-10 13:09 UTC, pvyhnal-generalbytes approved these changes

2021-11-10 14:39 UTC, filipocelka requested changes

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IExtensionContext.java
> +     * @return List of simplified identities (with only basic attributes without collections)
List of identities (with only basic attributes without related data represented by collections)

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IIdentity.java
> +public interface IIdentity extends IIdentitySimple {
Consider also moving `IOrganization getOrganization();` to `IIdentitySimple`

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IIdentitySimple.java
> +public interface IIdentitySimple {
Please add javadoc explaining purpose of this interface

Also please consider renaming it to `IIdentityBase`, `IIdentityWithoutRelations`, etc.

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_api/src/main/java/com/generalbytes/batm/server/extensions/IIdentitySimple.java
> +    String getNote();
Maybe remove - customers using this "new" interface won't need to have an option to use deprecated method

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/identity/IdentityExampleRestService.java
>      public String registerInner(String fiatCurrency, String externalId, BigDecimal limit, BigDecimal discount,
Since you've removed first method, you don't need `registerInner` anymore

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/identity/IdentityExampleRestService.java
> +    @Path("/findidentitiesbyphonenumber")
`/find-identities-by-phone-number`

2021-11-10 14:39 UTC, filipocelka commented on server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples/identity/IdentityExampleRestService.java
> +    @Path("/findidentitiesbyphonenumbersimple")
`/find-identities-by-phone-number-simple` but replace "simple" by something else after renaming IIdentitySimple

2021-11-11 07:30 UTC, filipocelka approved these changes

2021-11-11 09:20 UTC, merged